
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL';

export const ADD_STUDENT = 'ADD_STUDENT';
export const ADD_STUDENT_START = 'ADD_STUDENT_START';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';


export const ADD_TEACHER = 'ADD_TEACHER';
export const REMOVE_TEACHER = 'REMOVE_TEACHER';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';

export const ADD_LESSON = 'ADD_LESSON';
export const REMOVE_LESSON = 'REMOVE_LESSON';